# Enable tracing (generates a trace-timestamp.json file).
tracing: true
# The temperature used to generate samples.
temperature: 0.2
# Nucleus sampling probability cutoff.
top_p: 1
# The seed to use when generating random samples.
seed: 299792458
# The length of the sample to generate (in tokens).
sample_len: 500
# Penalty to be applied for repeating tokens, 1. means no penalty.
repeat_penalty: 1.3
# The context size to consider for the repeat penalty.
repeat_last_n: 150